// Policy facts come from the confirmed Website Pass #2 decisions and inspected
// implementation. No provider retention promises or jurisdiction clauses added.
export const privacySections = (links) => [
  ['overview', 'About this policy', `<p>Lumaunt is operated by Rayn. This policy explains how the macOS app, its supporting services, and this website process information. For privacy questions or requests, contact <a href="${links.privacyEmail}">privacy@lumaunt.app</a>.</p>`],
  ['information', 'Information processed', '<p>Information may include your Discord session credentials, presence configuration and text, images you choose to host, moderation submissions and results, optional crash reports, and technical information about requests to supporting services. Which information is processed depends on the features you use and your settings.</p>'],
  ['use', 'How information is used', '<p>Lumaunt uses this information to connect to Discord, publish Rich Presence, provide optional image hosting, moderate content, prevent abuse, maintain reliability, and troubleshoot problems. Moderation submissions and results may also be used for quality assurance, safety, troubleshooting, and evaluation of Lumaunt’s moderation systems.</p><p>Lumaunt does not sell personal information or use it for targeted advertising. This website currently has no analytics, advertising trackers, or marketing cookies.</p>'],
  ['authentication', 'Discord authentication', '<p>Discord session credentials are stored locally on your Mac. Sensitive Discord session and refresh credentials use the macOS Keychain. Lumaunt does not maintain a server-side Discord account database.</p><p>Lumaunt communicates with Discord to authorize your account, maintain the connection, and provide Rich Presence. Local credential storage does not mean that Discord information never leaves your device.</p>'],
  ['presence', 'Rich Presence', '<p>Presence configuration is primarily handled locally and communicated to Discord as needed to provide Rich Presence. Applied text, images, buttons, and timer information may be visible to other people through Discord. Presence text may also be sent for content moderation.</p>'],
  ['moderation', 'Content moderation', '<p>Lumaunt uses moderation systems involving OpenAI and Cloudflare services. Presence text may be submitted to these services when required by Lumaunt’s safety systems.</p><p>Lumaunt may retain moderation submissions and results for up to 90 days for quality assurance, safety, troubleshooting, and evaluation of Lumaunt’s moderation systems. This describes Lumaunt’s retention and does not promise a particular retention policy for each provider.</p>'],
  ['images', 'Hosted images', '<p>Hosted image uploads are optional. If you upload an image, it may be publicly accessible to anyone with its URL. Avoid uploading images that contain information you do not want shared.</p><p>Managed hosted images have selectable retention periods of 7, 30, or 90 days and can be manually deleted through Lumaunt. Lumaunt does not intentionally keep a second permanent copy after managed deletion or expiration. Third-party and network caches may temporarily retain copies outside Lumaunt’s direct control.</p><p>These managed retention options do not describe the availability or retention of images hosted elsewhere.</p>'],
  ['crashes', 'Optional crash reporting', '<p>Lumaunt uses Sentry for optional crash reporting. Reporting is disabled unless you enable it. When enabled, reports help diagnose crashes and may include technical details such as the app version, operating system, and stack traces.</p><p>The client is configured not to send default personally identifiable information and to scrub sensitive information from crash reports. These measures reduce exposure but cannot guarantee that accidental sensitive-data transmission is technically impossible.</p>'],
  ['logs', 'Technical information and backend logs', '<p>Cloudflare infrastructure may process an IP address, approximate IP-derived location, user agent, requested URL or path, and timing or network information. This information may be used for security, abuse prevention, reliability, and troubleshooting.</p><p>Lumaunt’s applicable Cloudflare Workers logs are currently retained for no longer than 7 days. This does not control every retention policy of Cloudflare as a third-party provider.</p>'],
  ['providers', 'Third-party providers', '<p>Providers relevant to Lumaunt currently include Discord for authentication and Rich Presence, Cloudflare for infrastructure and supporting services, OpenAI for moderation, and Sentry for optional crash reporting. Their services are subject to their own privacy policies and terms. Information sent to them may also be processed under those policies.</p>'],
  ['retention', 'Retention', '<p>Managed hosted images use the chosen 7-, 30-, or 90-day period, or can be deleted manually. Moderation submissions and results may be retained by Lumaunt for up to 90 days. Applicable Cloudflare Workers logs are retained for no longer than 7 days.</p><p>Lumaunt’s saved Discord session credentials and presence configurations are stored locally on your Mac. Disconnect Account removes Lumaunt’s saved Discord session credentials. Provider-side retention may differ. This policy does not establish a separate retention period for every category of local data or optional crash report.</p>'],
  ['security', 'Security', '<p>Lumaunt uses safeguards such as macOS Keychain storage for sensitive Discord session credentials and scrubbing for optional crash reports. No software, storage system, or transmission method can guarantee complete security. Keep your Mac secure and do not share access tokens, refresh tokens, Keychain secrets, or other private credentials in bug reports.</p>'],
  ['choices', 'Your choices and controls', '<ul><li>Use Disconnect Account to disconnect Lumaunt and remove its saved Discord session credentials.</li><li>Choose whether to use hosted image uploads, select a managed retention period, and manually delete managed hosted images.</li><li>Keep crash reporting disabled, or turn it off after enabling it.</li><li>Choose what text, artwork, and links you publish through Discord.</li></ul><p>For privacy questions or requests concerning information processed by Lumaunt, email <a href="'+links.privacyEmail+'">privacy@lumaunt.app</a>. Explain your request without including credentials. Information stored only on your Mac is not available through a server-side Discord account database.</p>'],
  ['age', 'Children and age requirements', '<p>Lumaunt is intended for users age 13 and older, subject to any higher minimum age required by applicable law or Discord’s requirements. If you believe a child below the applicable minimum age has provided information to Lumaunt, contact the privacy address.</p>'],
  ['international', 'International processing', '<p>Third-party providers may process information in countries other than the country where you live. Processing locations and safeguards depend on the provider and service. Lumaunt does not promise that all information is processed in a single country.</p>'],
  ['changes', 'Changes to this policy', '<p>This policy may change as Lumaunt’s features, services, or practices change. Updates will be published on this page with a revised last-updated date.</p>'],
  ['contact', 'Contact', `<p>Privacy questions and requests: <a href="${links.privacyEmail}">privacy@lumaunt.app</a>.</p><p>For technical help and bug reports, visit the <a href="/support/">Support page</a>.</p>`],
];

export const termsSections = (links) => [
  ['acceptance', 'Using Lumaunt', '<p>These Terms of Use apply to Lumaunt and its supporting services. By using them, you agree to these terms. If you do not agree, do not use Lumaunt or its services. Lumaunt is operated by Rayn.</p>'],
  ['description', 'What Lumaunt provides', '<p>Lumaunt is a native macOS application for creating and managing Discord Rich Presence. It offers local editing and previews, images, buttons, timers, presets, and supporting features such as optional hosted images and content moderation. Availability of features and supporting services may change.</p>'],
  ['discord', 'Discord and other third-party services', '<p>You must comply with Discord’s applicable rules and terms when using Lumaunt with Discord. Other third-party services used by Lumaunt are governed by their own applicable terms.</p><p>Lumaunt is not affiliated with or endorsed by Discord.</p>'],
  ['content', 'Your content', '<p>You are responsible for the text, artwork, links, and other content you put in your Rich Presence or submit to Lumaunt’s services. Only use content you have the right to use. Do not publish unlawful content, infringe others’ rights, expose private credentials, or use Lumaunt to harass or threaten people.</p>'],
  ['abuse', 'Service protections and prohibited abuse', '<p>Do not abuse Lumaunt or its backend services. Do not attempt to bypass moderation, rate limits, security checks, or other service protections. Do not use the services to distribute malicious content, disrupt service availability, or gain unauthorized access. Requests or content may be blocked by these protections.</p>'],
  ['images', 'Hosted image rules', '<p>Hosted image uploads are optional. Upload only images you have permission to use and that comply with these terms and applicable Discord rules. Hosted images may be publicly accessible by URL, so do not upload sensitive or private material.</p><p>Managed images are subject to your selected 7-, 30-, or 90-day retention period and can be manually deleted. Third-party or network caches may temporarily retain copies after deletion or expiration. Hosted images should not be relied on as permanent storage or a backup.</p>'],
  ['availability', 'Availability and software limitations', '<p>Lumaunt and its supporting services may change, become unavailable, or be interrupted. The software may contain bugs. Keep copies of important configurations and original images, and do not rely on uninterrupted operation.</p>'],
  ['licenses', 'Repository and software licenses', `<p>The source repository is available on <a href="${links.github}">GitHub</a>. Open-source components and repository materials may be governed by their applicable licenses. These terms do not replace or change any rights, conditions, or disclaimers provided by those licenses.</p>`],
  ['privacy', 'Privacy and user controls', '<p>The <a href="/privacy/">Privacy Policy</a> describes local credential storage, content moderation, optional image hosting, optional crash reporting, and technical request information. Use the app’s settings to manage hosted images and crash reporting.</p>'],
  ['changes', 'Changes to these terms', '<p>These terms may be updated as Lumaunt develops. Updated terms will be published here with a revised last-updated date. Review the current terms when using Lumaunt.</p>'],
  ['contact', 'Contact', `<p>For technical questions or bug reports, use the <a href="/support/">Support page</a> or <a href="${links.issues}">GitHub Issues</a>. For privacy questions or requests, email <a href="${links.privacyEmail}">privacy@lumaunt.app</a>.</p>`],
];
